Feat/get task by pagination
lovecolor/todoApp pull request #14
Opened 2021-08-11 06:14 UTC by lovecolor

2021-08-11 06:17 UTC, lovecolor commented
a coi Merge branch 'feat/removeTask' of https://github.com/lovecolor/todoApp … … ấy anh e cài cái extension kia để giữ mấy file cũ của git mà lúc commit nó lỗi tùm lum :v

2021-08-11 07:13 UTC, hoaikthai requested changes

2021-08-11 07:13 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +  let currentPage = queryParams.get("page") || 1
1. ko dùng biến let
2. viết 1 hook useQuery để get về obj query và hàm để sửa query
```ts
const { query, patchQuery } = useQuery<{ page: number }>(initialQuery)
```
3. thay đổi page chỉ cần đổi query params page, useAsync sẽ lấy page đó gọi API

2021-08-11 07:13 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +      setLoad(true)
có loading vs result mà e ko dùng đc hook useAsync chỗ này à

2021-08-11 07:13 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +type AllTaskRequest = {
```suggestion
type GetAllTaskRequest = {
```

2021-08-11 07:13 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +      const res = await api.get<AllTaskReponse>(`/task${params ? `?limit=${params.limit}&skip=${params.skip}` : ""}`)
https://github.com/axios/axios#example
coi gọi cách nào cho đơn giản tí, nhìn phức tạp quá

2021-08-11 07:13 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +  async (params?: AllTaskRequest): Promise<Task[] | undefined> => {
```suggestion
  async (req?: AllTaskRequest): Promise<Task[] | undefined> => {
```

2021-08-11 10:07 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  const [query, setQuery] = useState<T>(initialQuery)
a nhập đại query params trên url thì nó ko có tác dụng à e?

2021-08-11 10:12 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +  addTask: (...tasks: Task[]) => void
```suggestion
  addTasks: (tasks: Task[]) => void
```

2021-08-11 10:12 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +  const { query, patchQuery } = useQuery<{ page: number }>({ page: 1 })
th TaskProvider gánh nhiều responsibility quá nhỉ

2021-08-11 10:13 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  const [query, setQuery] = useState<T>(initialQuery)
cài thêm query-string mà dùng

2021-08-12 03:47 UTC, hoaikthai requested changes

2021-08-12 03:47 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +const NextBtn = styled(FabPrimary)`
NextBtn giống gần y PrevBtn, vậy thì tạo 1 component chung rồi 2 th này extend lại

2021-08-12 03:47 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  const patchQuery = (data) => {
patchQuery của e ko đổi đc params trên url

2021-08-12 03:47 UTC, hoaikthai commented on src/hooks/useQuery.ts
> +  const [query, setQuery] = useState<T>(initialQuery)
query của e ko get đc params trên url

2021-08-12 06:01 UTC, hoaikthai requested changes

2021-08-12 06:01 UTC, hoaikthai commented on src/components/buttons/BtnChangePage.ts
> +export const BtnChangPage = styled(FabPrimary)`
```suggestion
export const ButtonChangPage = styled(FabPrimary)`
```

2021-08-12 06:01 UTC, hoaikthai commented on src/components/buttons/BtnChangePage.ts
> +  z-index: 100;
z-index để làm gì e

2021-08-12 06:01 UTC, hoaikthai commented on src/components/buttons/FabPrimary.ts
> +export const FabPrimary = styled(Fab).attrs((props) => ({
```suggestion
export const ButtonFloatingPrimary = styled(Fab).attrs((props) => ({
```

2021-08-12 06:01 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +  // const location = useLocation()
bỏ hết comment vô ích

2021-08-12 06:01 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +          <PrevBtn onClick={() => changePage(+query.page - 1)}>
a tưởng query.page type number rồi?

2021-08-12 06:01 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +    if (tasks.length < perLoad) setTasks([...tasks, newTask])
append vào cuối à, a nghĩ task mới BE nó append ở đầu chứ

2021-08-12 06:01 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +  }
mỗi hàm define xong newline ra e

2021-08-12 06:01 UTC, hoaikthai commented on src/components/buttons/BtnChangePage.ts
> +export const BtnChangPage = styled(FabPrimary)`
Change page lại dùng Fab à, sao ko dùng button bt?

2021-08-12 06:04 UTC, lovecolor commented on src/pages/HomePage.tsx
> +          <PrevBtn onClick={() => changePage(+query.page - 1)}>
lúc parse nó ra lại thành string a e+ vô cái nó ra 11 lun

2021-08-12 06:44 UTC, lovecolor commented on src/components/buttons/BtnChangePage.ts
> +  z-index: 100;
xuống mobie nó đè 1 phần nhỏ lên task nên phải để z-index cho nó hiện lên cho đẹp anh

2021-08-12 06:45 UTC, lovecolor commented on src/pages/HomePage.tsx
> +    if (tasks.length < perLoad) setTasks([...tasks, newTask])
e add r load lại trang nó vẫn nằm cuối anh

2021-08-12 11:56 UTC, hoaikthai commented on src/components/tasks/TaskList.tsx
> +  handleEditTask: (editedTask: Task) => void
```suggestion
  onEditTask: (editedTask: Task) => void
```

2021-08-12 11:56 UTC, hoaikthai commented on src/components/tasks/TaskList.tsx
> +  handleRemoveTask: () => void
```suggestion
  onRemoveTask: () => void
```

2021-08-13 03:38 UTC, merged