upload Image
lovecolor/todoApp pull request #15
Opened 2021-08-13 08:05 UTC by lovecolor

2021-08-14 15:25 UTC, hoaikthai requested changes

2021-08-14 15:25 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +  uid: string
```suggestion
  userId: string
```
uid có nghĩa khác nhé

2021-08-14 15:25 UTC, hoaikthai commented on src/components/AvatarUser.tsx
> +  width: string
nên đổi thành size (cho phép nhận giá trị "small" | "medium" | "large"), ko cho set tự do như này, design chuẩn thì ko có nhiều loại size lắm đâu, còn muốn tự do thì cho custom css ở component dùng, ko truyền props như này

2021-08-14 15:25 UTC, hoaikthai commented on src/components/AvatarUser.tsx
> +export default function AvatarUser(props: AvatarUserProps) {
sao tự nhiên đổi qua function thường dùng r e?

2021-08-14 15:25 UTC, hoaikthai commented on src/components/AvatarUser.tsx
> +}
enter

2021-08-14 15:25 UTC, hoaikthai commented on src/components/AvatarUser.tsx
> +}
enter

2021-08-14 15:25 UTC, hoaikthai commented on src/components/AvatarUser.tsx
> +export default function AvatarUser(props: AvatarUserProps) {
đổi tên thành UserAvatar hoặc Avatar

2021-08-14 15:25 UTC, hoaikthai commented on src/components/AvatarUser.tsx
> +  border-radius: 50rem;
```suggestion
  border-radius: 50%;
```

2021-08-14 15:25 UTC, hoaikthai commented on src/components/AvatarUser.tsx
> +  border-radius: 50rem;
tại sao e dùng 50 rem?

2021-08-14 15:25 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +  urlImage: string | null
```suggestion
  avatarUrl: string | null
```

2021-08-14 15:25 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +      const resultGetImage = await api.getUserImage({ uid: result._id })
```suggestion
      const userAvatarUrl = await api.getUserImage({ uid: result._id })
```

2021-08-14 15:25 UTC, hoaikthai commented on src/pages/Login.tsx
> +      const imageUser = await api.getUserImage({ uid: result.user._id })
```suggestion
      const userAvatarUrl = await api.getUserImage({ uid: result.user._id })
```

2021-08-14 15:25 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +  })
enter

2021-08-14 15:25 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +  }
enter

2021-08-14 15:25 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +  right: 0;
e set đống này có ý nghĩa gì?

2021-08-14 15:25 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +            <OverlayUpLoadImage className="overlay">
className?

2021-08-14 15:25 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +  }
enter

2021-08-14 15:25 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +}
enter

2021-08-14 15:25 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +  const onChangeImage = (e) => {
```suggestion
  const handleChangeImage = (e) => {
```

2021-08-14 15:25 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +              <InputUploadImage onChange={onChangeImage} id="icon-button-file" accept="image/*" type="file" />
id????

2021-08-15 06:49 UTC, lovecolor commented on src/components/AvatarUser.tsx
> +export default function AvatarUser(props: AvatarUserProps) {
e gõ tắt rfc trong vscode cái nó ra đoạn lệnh rứa á a :v

2021-08-15 07:31 UTC, lovecolor commented on src/pages/UserProfile.tsx
> +            <OverlayUpLoadImage className="overlay">
để e hover vô tấm ảnh thì nó hiện cái button camera lên để đổi ảnh

2021-08-15 07:39 UTC, lovecolor commented on src/pages/UserProfile.tsx
> +              <InputUploadImage onChange={onChangeImage} id="icon-button-file" accept="image/*" type="file" />
tại cái input này bị ẩn nên dùng cái button camera để chọn file nên phải đặt id nó ms nhận dc a

2021-08-15 07:48 UTC, lovecolor commented on src/pages/UserProfile.tsx
> +  right: 0;
cho nó lắp đầy thằng cha

2021-08-15 10:27 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +            <OverlayUpLoadImage className="overlay">
e có cách khác, ko cần phải thêm className

2021-08-15 10:28 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +              <InputUploadImage onChange={onChangeImage} id="icon-button-file" accept="image/*" type="file" />
e có cách khác ko cần thêm id

2021-08-15 10:39 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +  right: 0;
vậy sao ko set width vs height?

2021-08-16 07:32 UTC, lovecolor commented
@hoaikthai

2021-08-16 09:07 UTC, hoaikthai requested changes

2021-08-16 09:07 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +const IcBtnCamera = styled(IconButton)`
```suggestion
const CameraIconButton = styled(IconButton)`
```
có mấy chữ cũng viết tắt làm gì e? Tên component chứ phải class đâu

2021-08-16 09:07 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +    div {
https://styled-components.com/docs/advanced#referring-to-other-components

2021-08-16 09:07 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +  left: 0;
có cần thiết nữa ko?

2021-08-16 09:07 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +const Avatar = styled.div`
CustomAvatar là component UserAvatar rồi còn Avatar này là gì? Đặt tên lại rõ ràng

2021-08-16 09:07 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +              </Choosefile>{" "}
{" "} để làm gì nhỉ?, e bỏ đi rồi save lại có bị format như vậy ko?

2021-08-16 09:07 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +const OverlayUpLoadImage = styled.div`
```suggestion
const UpLoadImageOverlay = styled.div`
```

2021-08-16 09:07 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +const Choosefile = styled.div`
cái này có phải là hàm đâu sao đặt tên như động từ vậy e, còn sai convention nữa

2021-08-16 09:07 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +                <IcBtnCamera>
button này bấm vào có tác dụng gì?

2021-08-16 09:29 UTC, lovecolor commented on src/pages/UserProfile.tsx
> +                <IcBtnCamera>
show cái cửa sổ chọn file lên giống của cách đổi avatar của thằng facebook cũ ấy a

2021-08-16 11:04 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +                <IcBtnCamera>
sao a ko thấy handle click cho button này hè

2021-08-17 06:48 UTC, lovecolor commented on src/pages/UserProfile.tsx
> +                <IcBtnCamera>
e để cái input nằm trên cái button này r opacity:0 để khi click vào là tg input nó nhận r mở cái cửa sổ chọn file lên nên k có handle ạ

2021-08-17 07:19 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +                <IcBtnCamera>
sao lằng nhằng vậy, e muốn kiểu vậy thì cho nó display none luôn rồi set event click button.

code ảo diệu thì chỉ tổ mất thời gian của người vào sau hay của chính e sau vài ba tháng quay lại thôi

2021-08-17 07:49 UTC, lovecolor commented on src/pages/UserProfile.tsx
> +                <IcBtnCamera>
làm sao set event cho nó mở cái cửa sổ chọn file lên a

2021-08-17 07:51 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +                <IcBtnCamera>
tạo ref cho cái input, khi click button thì trigger click cho cái input

2021-08-17 08:46 UTC, lovecolor commented
@hoaikthai

2021-08-18 02:56 UTC, merged