Feat/register
lovecolor/todoApp pull request #2
Opened 2021-07-13 15:59 UTC by lovecolor

@hoaikthai

2021-07-14 02:24 UTC, hoaikthai commented on src/services/api/createApiClient.ts
> +    (response) => {
```
(response) => response,
(error) => {
  ...
```

2021-07-14 02:25 UTC, hoaikthai commented on yarn.lock
> +"@reduxjs/toolkit@^1.6.0":
bỏ trong package.json rồi install lại cho nó update e

2021-07-14 02:26 UTC, hoaikthai commented on src/pages/Register.tsx
> +.err{
tạo styled component Error

2021-07-14 02:26 UTC, hoaikthai commented on src/pages/Register.tsx
> +                <TextField required className="field" type="text" name="name" placeholder="Name"></TextField>
bỏ hết class

2021-07-14 02:26 UTC, hoaikthai commented on src/pages/Register.tsx
> +.actions{
tạo styled component Actions

2021-07-14 02:27 UTC, hoaikthai commented on src/pages/Register.tsx
> +    &>button{
dùng button của Material UI, có chỉnh gì thì tạo styled component ActionButton

2021-07-14 02:42 UTC, hoaikthai commented on package.json
> +
e ko có format cho file json à?

2021-07-14 02:43 UTC, hoaikthai commented on src/links.ts
> +    register:()=>"/register"
format

2021-07-14 02:43 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +    return <EmptyLayout><h1>HomePage</h1></EmptyLayout>
```suggestion
    return <MainLayout><h1>HomePage</h1></EmptyLayout>
```

2021-07-14 02:44 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +const getLoggedInUserviaToken =
```suggestion
const getCurrentUser =
```

2021-07-14 03:14 UTC, hoaikthai commented on src/hooks/use-async.ts
> +import { useState, useCallback } from "react"
rename tên file thành useAsync

2021-07-14 03:14 UTC, hoaikthai commented on src/contexts/auth-context.tsx
> +import React from "react";
rename tên file thành AuthProvider

2021-07-14 03:15 UTC, hoaikthai commented on src/contexts/auth-context.tsx
> +export const AuthContextProvider: React.FC = (props) => {
```suggestion
export const AuthProvider: React.FC = (props) => {
```

2021-07-14 03:17 UTC, hoaikthai commented on src/contexts/auth-context.tsx
> +    const { run, result, error } = useAsync(useAppApiClient().getLoggedInUserviaToken)
```suggestion
   const api = useAppApiClient()
    const currentUser = useAsync(api.getCurrentUser)
```

2021-07-14 03:21 UTC, hoaikthai commented on src/contexts/auth-context.tsx
> +import React from "react";
sorry hôm qua a nhìn lộn, trong này sẽ có hàm signUp, login, logout gọi các API tương ứng (dùng useAsync)
contextValue sẽ bao gồm các hàm này + user, loading và error

2021-07-14 03:22 UTC, hoaikthai commented on src/contexts/auth-context.tsx
> +    user: any,
tạo type cho `user`

2021-07-14 03:23 UTC, hoaikthai commented on src/contexts/auth-context.tsx
> +    isLoggedIn: boolean,
có thể biết isLoggedIn bằng cách check user có tồn tại hay ko
token có trong localStorage rồi, cũng ko cần bỏ vào làm gì

2021-07-14 03:35 UTC, hoaikthai commented on src/pages/Register.tsx
> +    const { run, loading, error, result } = useAsync(useAppApiClient().register)
register sẽ gọi authCtx.register

2021-07-14 04:39 UTC, lovecolor commented on package.json
> +
cai ni format tay hả a

2021-07-14 05:14 UTC, lovecolor commented on src/contexts/auth-context.tsx
> +import React from "react";
ủa a khi mình register thì mình dùng useAsync trong pageRegister r có kq trả về thành công r mình ms đưa data vào login của athCtx hay mình đưa data vô hàm signUp trong ctxAuth r chạy async trong đó

2021-07-14 05:25 UTC, lovecolor commented on src/contexts/auth-context.tsx
> +import React from "react";
rứa mình phải tạo 3 cái useAsync tương ứng với 3 hàm hả a

2021-07-14 05:35 UTC, hoaikthai commented on src/contexts/auth-context.tsx
> +import React from "react";
3 useAsync nhưng mà ko cho chạy ngay, 3 hàm đó sẽ run 3 cái useAsync này và update state loading, error của context

2021-07-14 08:39 UTC, hoaikthai requested changes

2021-07-14 08:39 UTC, hoaikthai commented on src/App.tsx
> +              )}
không như này đc à e
```tsx
              {!isLoggedIn && (
                <>
                  <Route path={links.login()}>
                    <Login />
                  </Route>
                  <Route path={links.register()}>
                    <Register />
                  </Route>
                </>
              )}
```
chỉ check isLoggedIn hay !isLoggedIn 1 lần thôi, group hết lại cho dễ nhìn

2021-07-14 08:39 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +type user = {
tạo type User trong src/services/api/types

2021-07-14 08:39 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +type RegisterRequest = {
tạo type RegisterRequest trong src/services/api/types

2021-07-14 08:39 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +type LoginRequest = {
tạo type LoginRequest trong src/services/api/types

2021-07-14 08:39 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +const AuthContext = React.createContext<{
```suggestion
const AuthContext = createContext<{
```

2021-07-14 08:39 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +  const signUpHandler = (data) => {
```suggestion
  const signUp = (data) => {
```

2021-07-14 08:39 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +  const loginHandler = (data) => {
```suggestion
  const login = (data) => {
```

2021-07-14 08:39 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +  const logoutHandler = () => {
```suggestion
  const logout = () => {
```

2021-07-14 08:39 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +      console.log("token")
bỏ

2021-07-14 08:39 UTC, hoaikthai commented on src/pages/Register.tsx
> +const useStyles = makeStyles((theme) => ({
mình dùng styled-component rồi, ko cần phải dùng makeStyles của MaterialUI

2021-07-14 08:39 UTC, hoaikthai commented on src/pages/Register.tsx
> +        <CssBaseline />
a có bọc ở ngoài App.tsx rồi trong này vần còn cần á?

2021-07-14 08:39 UTC, hoaikthai commented on src/pages/Register.tsx
> +        <div className={classes.paper}>
dùng styled-component, ko dùng class
vd:
```tsx
const CustomPaper = styled(Paper)``
```

2021-07-14 08:39 UTC, hoaikthai commented on src/pages/Register.tsx
> +              <Button type="submit" fullWidth variant="contained" color="primary" className={classes.submit}>
button kiểu này có thể e sẽ reuse lại nhiều, tạo trong src/components/buttons/ButtonPrimary.tsx
```
export const ButtonPrimary = styled(Button).attrs((props) => ({ color: "primary", variant: "contained", ...props }))``
```

2021-07-14 08:39 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +type RegisterRequest = {
nếu có tạo type ở src/services/api/types rồi thì bỏ definition ở đây và import dùng

2021-07-14 08:43 UTC, lovecolor commented on src/App.tsx
> +              )}
ok

2021-07-14 08:44 UTC, hoaikthai commented on src/pages/Register.tsx
> +          <Typography component="h1" variant="h5">
component h1 mà variant h5 khó hiểu nha, sao ko component h5 luôn e

2021-07-14 08:47 UTC, hoaikthai commented on src/pages/Register.tsx
> +                  id="name"
ko cần id

2021-07-14 08:49 UTC, hoaikthai commented on src/pages/Register.tsx
> +                  variant="outlined"
nếu như e dùng TextField variant này nhiều quá thì e có thể tạo src/component/TextFieldOutlined.tsx
```tsx
export const TextFieldOutlined = styled(TextField).attrs((props) => ({ variant: "outlined", ...props }))``
```

2021-07-14 08:50 UTC, lovecolor commented on src/pages/Register.tsx
> +        <CssBaseline />
e vo template họ xem cop theo :v

2021-07-14 09:44 UTC, hoaikthai commented on src/components/buttons/ButtonPrimary.tsx
> +  margin: 1rem 0;
e cần chỉnh margin hay style ngoài e có thể Custom ngoài page component

2021-07-14 09:44 UTC, hoaikthai commented on src/pages/Login.tsx
> +              margin="normal"
tại sao cần cái này e, e cần chỉnh thì e có thể tạo 1 styled-component
```tsx
const CustomTextField = styled(TextFieldOutlined)``
```

2021-07-14 09:44 UTC, hoaikthai commented on src/pages/Login.tsx
> +const useStyles = makeStyles((theme) => ({
bỏ hết

2021-07-14 09:44 UTC, hoaikthai commented on src/pages/Login.tsx
> +              id="email"
bỏ

2021-07-14 09:44 UTC, hoaikthai commented on src/pages/Login.tsx
> +              id="password"
bỏ

2021-07-14 09:44 UTC, hoaikthai commented on src/pages/Login.tsx
> +function Copyright() {
không cần lắm, thôi bỏ đi :D

2021-07-14 09:44 UTC, hoaikthai commented on src/pages/Register.tsx
> +function Copyright() {
bỏ

2021-07-14 10:08 UTC, lovecolor commented
@hoaikthai

2021-07-14 10:15 UTC, hoaikthai commented on src/pages/Login.tsx
> +              margin="normal"
tại sao e lại cần margin="normal"?

2021-07-14 10:15 UTC, hoaikthai commented on src/pages/Login.tsx
> +margin:.5rem 0;
format

2021-07-14 10:24 UTC, lovecolor commented
@hoaikthai

2021-07-15 02:36 UTC, hoaikthai requested changes

2021-07-15 02:36 UTC, hoaikthai commented on src/pages/Register.tsx
> +    setFormValue((prevState) => {
```suggestion
    const { name, value } = e.target
    setFormValue({ ...formValue, [name]: value })
```

2021-07-15 02:36 UTC, hoaikthai commented on src/pages/Register.tsx
> +    setFormValue((prevState) => {
cách của e hiện tại thì ổn 👌

2021-07-15 07:27 UTC, hoaikthai commented on src/App.tsx
> +  const isLoggedIn = authCtx.user != null
```suggestion
  const isLoggedIn = !!authCtx.user
```

2021-07-15 07:27 UTC, hoaikthai commented on src/App.tsx
> +  const token = localStorage.getItem("token")
nếu dùng nhiều vậy thì bỏ token vào AuthContext lại vậy 😅

2021-07-15 07:49 UTC, lovecolor commented
@hoaikthai

2021-07-15 07:50 UTC, hoaikthai approved these changes

2021-07-15 07:50 UTC, merged