Feat/update profile
lovecolor/todoApp pull request #3
Opened 2021-07-15 10:23 UTC by lovecolor

2021-07-15 10:23 UTC, lovecolor commented
@hoaikthai

2021-07-15 11:03 UTC, hoaikthai requested changes

2021-07-15 11:03 UTC, hoaikthai commented on src/App.tsx
> +                {isLoggedIn && (
sao ko bỏ vô group ở dưới luôn e?

2021-07-15 11:03 UTC, hoaikthai commented on src/components/layout/MainNavigation.tsx
> +    console.log(anchorEl)
bỏ

2021-07-15 11:03 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +  update: (data: UpdateUserRequest) => void
ủa update đâu liên quan gì tới auth đâu e?

2021-07-15 11:03 UTC, hoaikthai commented on src/services/api/types/UpdateUserRequest.ts
> +export type UpdateUserRequest = {
chỉ dùng mỗi cho api update thì nên define trong `createApiClient.ts` ko cần export

2021-07-15 11:03 UTC, hoaikthai commented on src/services/api/types/LoutoutReponse.ts
> +export type LogoutReponse = {
chỉ dùng mỗi cho api update thì nên define trong `createApiClient.ts` ko cần export

2021-07-15 11:03 UTC, hoaikthai commented on src/services/api/types/UpdateUserResponse.ts
> +import { User } from "./User"
chỉ dùng mỗi cho api update thì nên define trong `createApiClient.ts` ko cần export

2021-07-15 11:03 UTC, hoaikthai commented on src/components/layout/MainNavigation.tsx
> +              id="menu-appbar"
có cần ko?

2021-07-15 11:03 UTC, hoaikthai commented on src/components/layout/MainNavigation.tsx
> +export const MainNavigation: React.FC = (props) => {
```suggestion
export const Navbar: React.FC = (props) => {
```
đồng thời rename thành Navbar luôn
bỏ file này ở ngoài components luôn

2021-07-15 11:03 UTC, hoaikthai commented on src/components/layout/MainNavigation.tsx
> +export const MainNavigation: React.FC = (props) => {
props component nên define type và export

2021-07-15 11:03 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +    console.log(formValue)
bỏ

2021-07-15 11:03 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +              <Typography align="center" variant="h6">
h1, h2, ... hn là các heading (đầu đề), nếu chỉ là text bt thì e có thể dùng thẻ p hoặc span, cần sửa style thì custom lại

2021-07-15 14:09 UTC, lovecolor commented on src/contexts/AuthProvider.tsx
> +  update: (data: UpdateUserRequest) => void
update xong nó trả về user mình phải set lại user thì mình nên để hàm update trong đó hay nên update ở ngoài r gọi setUser trong đó a

2021-07-15 14:20 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
> +  update: (data: UpdateUserRequest) => void
update xong gọi getCurrentUser

2021-07-16 07:45 UTC, lovecolor commented on src/App.tsx
> +                {isLoggedIn && (
bỏ vô lúc đầu chưa login thì làm sao nó redirect sang trang login dc a

2021-07-16 07:57 UTC, hoaikthai commented on src/App.tsx
> +                {isLoggedIn && (
à a nhìn lộn :D tưởng cùng condition

2021-07-16 12:24 UTC, lovecolor commented on src/services/api/types/UpdateUserResponse.ts
> +import { User } from "./User"
có dùng trong authCtx nữa a

2021-07-16 12:37 UTC, lovecolor commented
@hoaikthai

2021-07-19 00:23 UTC, hoaikthai commented on src/components/NavBar.tsx
> +            <Menu
e thử tự build 1 component Dropdown thay vì dùng Menu xem :)

2021-07-19 00:36 UTC, hoaikthai requested changes

2021-07-19 00:36 UTC, hoaikthai commented on src/components/NavBar.tsx
> +            <Menu
e thử tự build 1 component Dropdown thay vì dùng Menu xem :)

2021-07-19 00:36 UTC, hoaikthai commented on src/components/NavBar.tsx
> +            <Typography variant="h6">Todos</Typography>
tạo component Heading6 trong src/components/text

2021-07-19 00:36 UTC, hoaikthai commented on src/pages/Register.tsx
> +              <Link href="/login" variant="body2">
dùng Link của react-router

2021-07-19 00:36 UTC, hoaikthai commented on src/pages/Login.tsx
> +              <Link href="/register" variant="body2">
dùng Link của react-router

2021-07-19 00:36 UTC, hoaikthai commented on src/pages/Login.tsx
> +    if (result) {
login fail thì sao e

2021-07-19 00:36 UTC, hoaikthai commented on src/contexts/AuthProvider.tsx
>  const AuthContext = createContext<{
giờ mình sửa lại, AuthContext có
user, setUser, token

2021-07-19 06:59 UTC, lovecolor commented on src/contexts/AuthProvider.tsx
>  const AuthContext = createContext<{
e thấy token k cần truy xuất nhiều nó chỉ dùng ở chỗ cái router mà nếu mình truy xuất token trong context ra thì ban đầu token nó = null nên nó redirect sang trang login lun mà chưa kịp lấy token trên localstorage xuống nữa nên e lấy token trong app.tsx lun thì tránh dc cái case nớ

2021-07-19 08:04 UTC, lovecolor commented on src/pages/Login.tsx
> +    if (result) {
fail thì nó trả bad request thì cái useAsync nó bắt dc error  show cái error ra thôi a

2021-07-19 09:30 UTC, hoaikthai requested changes

2021-07-19 09:30 UTC, hoaikthai commented on src/components/Dropdown.tsx
> +export const Dropdown: React.FC<{ label: ReactElement; actions: { name: string; handle: (...data: any) => any }[] }> = (
tạo type cho props

2021-07-19 09:30 UTC, hoaikthai commented on src/pages/Login.tsx
> +  const handleLogin = useAsync(async (data: LoginRequest) => {
```suggestion
  const login = useAsync(async (data: LoginRequest) => {
```

2021-07-19 09:30 UTC, hoaikthai commented on src/pages/Register.tsx
> +  const handleSignUp = useAsync(async (data: RegisterRequest) => {
```suggestion
  const signup = useAsync(async (data: RegisterRequest) => {
```

2021-07-19 09:30 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +      if (result) {
handle ở chỗ e trigger event, tránh dùng useEffect khi có thể vì nó phức tạp hóa component

2021-07-19 10:54 UTC, lovecolor commented
@hoaikthai

2021-07-20 02:19 UTC, merged