Feat/get all task
lovecolor/todoApp pull request #4
Opened 2021-07-20 07:49 UTC by lovecolor

2021-07-20 07:49 UTC, lovecolor commented
@hoaikthai

2021-07-20 09:35 UTC, hoaikthai requested changes

2021-07-20 09:35 UTC, hoaikthai commented on src/components/tasks/TaskList.tsx
> +  grid-template-columns: ${() => {
tìm cách khác

2021-07-20 09:35 UTC, hoaikthai commented on src/components/tasks/TaskItem.tsx
> +        <ButtonPrimary variant="contained" color="primary" startIcon={<EditIcon />}>
đã dùng ButtonPrimary rồi còn truyền color primary nữa à e?

2021-07-20 09:35 UTC, hoaikthai commented on src/components/tasks/TaskItem.tsx
> +import { CustomSpan } from "../../pages/UserProfile"
ko import component từ component ko liên quan, có thể duplicate nếu cần

2021-07-20 09:35 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +import { useEffect } from "react"
có cần phải tạo context ko e?

2021-07-20 09:35 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +export const CustomSpan = styled.span`
bỏ export, custom component là của riêng component này

2021-07-20 09:37 UTC, lovecolor commented on src/contexts/TaskProvider.tsx
> +import { useEffect } from "react"
sau ni nó update ở nhiều chỗ nên e tạo ctx để khỏi phải truyền nhiều hàm vào component con

2021-07-21 03:17 UTC, lovecolor commented
@hoaikthai

2021-07-21 03:49 UTC, hoaikthai requested changes

2021-07-21 03:49 UTC, hoaikthai commented on src/components/tasks/TaskList.tsx
> +  const { tasks } = taskCtx
lấy task từ props, ko lấy từ ctx, giả dụ mình mà có nhiều task list thì component này ko reuse đc

2021-07-21 03:49 UTC, hoaikthai commented on src/components/tasks/TaskList.tsx
> +export const TaskList: React.FC = (props) => {
define type + export type cho props

2021-07-21 03:49 UTC, hoaikthai commented on src/pages/UserProfile.tsx
> +import { GridContainer, Loading } from "./Register"
ko dùng component từ page khác, nếu có dùng chung thì bỏ vô component

2021-07-21 03:49 UTC, hoaikthai commented on src/components/tasks/TaskItem.tsx
> +export const TaskItem: React.FC<{
```suggestion
export TaskItemProps = {
  task: Task
}

export const TaskItem = (props: TaskItemProps) => {
```

2021-07-21 04:40 UTC, lovecolor commented
@hoaikthai

2021-07-22 03:00 UTC, hoaikthai requested changes

2021-07-22 03:00 UTC, hoaikthai commented on src/components/UI/GridContainer.tsx
> +import styled from "styled-components"
để trong src/components/Grid
UI chung chung quá, cái nào chả là UI e :)

2021-07-22 03:00 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +// import { Error, Loading } from "../pages/Register"
bỏ

2021-07-22 03:00 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +    getAllTask.run()
e chưa extend useAsync để chạy ngay khi gọi à, đỡ phải dùng 2 cái useEffect

2021-07-22 07:44 UTC, lovecolor commented
@hoaikthai

2021-07-23 03:43 UTC, hoaikthai requested changes

2021-07-23 03:43 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +      {getAllTask.loading && <Loading>Loading...</Loading>}
e đang ràng buộc mọi page dùng TaskContext phải show chung 1 loại loading, 1 loại error, 1 loại task list,
lỡ có page a muốn khi load task list loading là 1 spinner thay vì text hay hiện error kiểu khác thì sao?

2021-07-23 03:43 UTC, hoaikthai commented on src/hooks/useAsync.ts
> +const useAsync = (asyncFuntion: (...data: any) => any, isRun = false) => {
```suggestion
const useAsync = (asyncFuntion: (...data: any) => any, immediate = false) => {
```
isRun cũng sai ngữ pháp rồi

2021-07-23 07:03 UTC, lovecolor commented
@hoaikthai

2021-07-26 02:47 UTC, merged