Feat/add new task
lovecolor/todoApp pull request #5
Opened 2021-07-26 07:50 UTC by lovecolor

@hoaikthai

2021-07-27 02:43 UTC, hoaikthai requested changes

2021-07-27 02:43 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +        BackdropComponent={Backdrop}
có cần thiết ko?

2021-07-27 02:43 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +    if (value.length > 0) {
```
if (value.length === 0) return

// submit logic
```

2021-07-27 02:43 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +  const [listTask, setListTask] = useState<Task[]>([])
để làm gì đây e?

2021-07-27 02:43 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +  const api = useAppApiClient()
để làm gì?

2021-07-27 02:43 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +  async (description: string): Promise<Task | undefined> => {
tạo type cho request, tham số cùa hàm là cái type đó, ko truyền thẳng value như này

2021-07-27 02:43 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +  useEffect(() => {
có cần ko, a thấy e cho chạy ngay rồi mà?

2021-07-27 02:43 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +  async (description: string): Promise<Task | undefined> => {
ngoài ra body API này còn có `completed` nữa e, optional

2021-07-27 02:43 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +      enqueueSnackbar(`${submitLabel} fail!`, { variant: "error" })
```suggestion
      enqueueSnackbar(`${submitLabel} failure!`, { variant: "error" })
```

2021-07-27 02:43 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +          <form onSubmit={submitHandler}>
thêm 1 checkbox để set `completed`

2021-07-27 02:43 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +  label: ReactElement
này dùng làm gì e, a ko thấy

2021-07-27 02:43 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +      let requestData
`const requestData = props.task ? /* build update request */ : /* build create request */`

2021-07-27 06:53 UTC, lovecolor commented on src/components/tasks/TaskForm.tsx
> +        BackdropComponent={Backdrop}
dòng số mấy a

2021-07-27 06:58 UTC, lovecolor commented on src/services/api/createAppApiClient.ts
> +  async (description: string): Promise<Task | undefined> => {
e test api thấy thêm description là nó tự tạo completed = false

2021-07-27 07:02 UTC, lovecolor commented on src/components/tasks/TaskForm.tsx
> +  label: ReactElement
là submitLabel là cái text hiển thị cho nút sub trong form
onAction là hàm thực hiện sau khi thực hiện apiFuntion
apiFuntion là api chạy khi bấm submit , mà e nghĩ gộp 2 hàm lm 1 tiện hơn 
còn label là cái component hiển thị cho nút modal

2021-07-27 07:03 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +  async (description: string): Promise<Task | undefined> => {
đúng rồi, còn khi mình muốn tạo 1 task đã done thì truyền completed = true đc

2021-07-27 07:03 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +        BackdropComponent={Backdrop}
74 đó e

2021-07-27 07:07 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +  label: ReactElement
à a thấy r

2021-07-27 07:48 UTC, lovecolor commented on src/components/tasks/TaskForm.tsx
> +        BackdropComponent={Backdrop}
cái ni để nó hiện lên mượt hơn a

2021-07-27 07:49 UTC, lovecolor commented
@hoaikthai

2021-07-27 09:12 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +        BackdropComponent={Backdrop}
a ko nghĩ e cần phải specify `BackdropComponent` :v
mặc định nó đã vậy rồi

2021-07-27 09:40 UTC, lovecolor commented on src/components/tasks/TaskForm.tsx
> +        BackdropComponent={Backdrop}
e xóa đi thấy nó hiện thẳng lên chứ k transition :v

2021-07-28 02:21 UTC, hoaikthai requested changes

2021-07-28 02:21 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +    try {
sao try catch ở đây nữa e hè

2021-07-28 02:21 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +  const getAllTask = useAsync(api.getAllTask, true)
```suggestion
  const getAllTasks = useAsync(api.getAllTasks, true)
```

2021-07-28 02:21 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
>      getAllTask: getAllTask(api),
```suggestion
    getAllTasks: getAllTasks(api),
```

2021-07-28 06:58 UTC, lovecolor commented on src/components/tasks/TaskForm.tsx
> +    try {
gọi api mà trả về undefine thì e nhã ra 1 cái error cho nó bắt nếu k có error thì mới close cái modal lại

2021-07-28 07:04 UTC, lovecolor commented
@hoaikthai

2021-07-28 09:22 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +    try {
có error thì nó ở bị bắt ở trong useAsync rồi, ko phải vậy à?

2021-07-28 09:23 UTC, hoaikthai commented on src/components/tasks/NewTask.tsx
> +      throw new Error("Add failure!")
throw làm gì nữa e?

2021-07-28 09:42 UTC, lovecolor commented on src/components/tasks/NewTask.tsx
> +      throw new Error("Add failure!")
throw để nó nhã ra lỗi bên modal nó bắt trong try catch á a nếu k có lỗi thì nó thành công thì mình ms close modal

2021-07-28 10:03 UTC, hoaikthai commented on src/components/tasks/NewTask.tsx
> +      throw new Error("Add failure!")
mình ko nên xử lý kiểu "hack" như vậy, người khác đọc vào sao biết đc e throw lỗi để đóng modal đâu

2021-07-28 13:54 UTC, lovecolor commented on src/components/tasks/TaskForm.tsx
> +    try {
ở hàm api có try catch r nên useAsync k bắt dc

2021-07-28 13:55 UTC, lovecolor commented
@hoaikthai

2021-07-29 03:43 UTC, merged