Feat/update task
lovecolor/todoApp pull request #6
Opened 2021-07-30 07:57 UTC by lovecolor

@hoaikthai

2021-08-02 01:51 UTC, hoaikthai requested changes

2021-08-02 01:51 UTC, hoaikthai commented on src/App.tsx
> +                    {/* {!isLoggedIn && <Redirect to={links.login()}></Redirect>} */}
ko commit comment code trừ todo

2021-08-02 01:51 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +      console.log(error)
bỏ

2021-08-02 01:51 UTC, hoaikthai commented on src/components/tasks/TaskList.tsx
> +        <TaskItem task={task} key={id} id={id}></TaskItem>
id ở đây là index của task trong mảng tasks chứ đâu phải id thật

2021-08-02 01:51 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +    console.log(tasks)
console.log?

2021-08-02 01:51 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +    setTasks([...tasks.slice(0, data.id), data.newData, ...tasks.slice(data.id + 1)])
xử lý cồng kềnh

2021-08-02 01:51 UTC, hoaikthai commented on src/services/api/createAppApiClient.ts
> +  async (data: UpdateTaskRequest): Promise<Task | undefined> => {
```suggestion
  async (req: UpdateTaskRequest): Promise<Task | undefined> => {
```

2021-08-02 01:51 UTC, hoaikthai commented on src/services/api/types/Task.ts
> -  _id: string
sao lại bỏ nhỉ?

2021-08-02 01:51 UTC, hoaikthai commented on src/App.tsx
>                      <TaskProvider>
như vậy là homepage chỉ có thể có 1 task list thôi à?

2021-08-02 01:51 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +  onAction: (data: any) => void
any?

2021-08-02 01:51 UTC, hoaikthai commented on src/components/tasks/UpdateTask.tsx
> +import React from "react"
a ko thấy ý nghĩa việc tạo component này với NewTask, logic quá đơn giản, có thể bỏ ở ngoài component sử dụng đc

2021-08-02 01:51 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +  const [description, setDescription] = useState(props.id ? taskCtx.tasks[props.id].description : "")
sao ko truyền task làm props cho khỏe

2021-08-02 07:38 UTC, lovecolor commented
@hoaikthai

2021-08-03 02:30 UTC, hoaikthai requested changes

2021-08-03 02:30 UTC, hoaikthai commented on src/App.tsx
> +  const isLoggedIn = true
gì đây e

2021-08-03 02:30 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +    const taskIdEdited = tasks.findIndex((task) => task._id === editedTask._id)
```suggestion
    const editedTaskIndex = tasks.findIndex((task) => task._id === editedTask._id)
```

2021-08-03 02:30 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +    const taskIdEdited = tasks.findIndex((task) => task._id === editedTask._id)
rồi find ra -1 thì sao, giải quyết

2021-08-03 02:30 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
>    onAction: (task: Task) => void
```suggestion
  onSubmit: (task: Task) => void
```

2021-08-03 02:30 UTC, hoaikthai commented on src/components/tasks/TaskItem.tsx
> +    } catch (error) {
đoạn code trên throw lỗi khi nào

2021-08-03 02:35 UTC, hoaikthai commented on src/contexts/TaskProvider.tsx
> +    newTasks[taskIdEdited] = editedTask
không sửa mảng kiểu mutable như này
```ts
cosnt updatedTasks = tasks.map(task => task._id === editedTask ? editedTask : task)
```

2021-08-03 02:36 UTC, hoaikthai commented on src/components/tasks/TaskForm.tsx
> +    } catch (error) {
chỗ nào throw lỗi?

2021-08-03 05:19 UTC, lovecolor commented on src/App.tsx
> +  const isLoggedIn = true
cho nó vô dc trang homepage e ms check code dc :v

2021-08-03 05:33 UTC, lovecolor commented
@hoaikthai

2021-08-03 14:21 UTC, hoaikthai commented on src/pages/HomePage.tsx
> +          label={
theo như e dùng thì cái này là button chứ có phải label đâu

2021-08-03 14:21 UTC, hoaikthai commented on src/components/tasks/TaskItem.tsx
> +  const btnEdit = <ButtonPrimary startIcon={<EditIcon />}>Edit</ButtonPrimary>
cũng ko phức tạp mấy để tạo biến

2021-08-04 04:11 UTC, lovecolor commented
@hoaikthai

2021-08-04 07:06 UTC, hoaikthai commented on src/components/tasks/TaskItem.tsx
> +  const btnEdit = <ButtonPrimary startIcon={<EditIcon />}>Edit</ButtonPrimary>
chưa rep/fix đừng bấm resolve nha e

2021-08-04 08:46 UTC, lovecolor commented on src/components/tasks/TaskItem.tsx
> +  const btnEdit = <ButtonPrimary startIcon={<EditIcon />}>Edit</ButtonPrimary>
ủa e sửa chỗ đó r mà a e bỏ thẳng nó vô chỗ truyền props lun r

2021-08-05 03:24 UTC, merged